services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: duynguyen03/smart-device-service
    container_name: smart-device-service
    ports:
      - "8080:8080"
    networks:
      - smart-device-network
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: smart-device-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12332145
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    networks:
      - smart-device-network

networks:
  smart-device-network:
    driver: bridge